### PR TITLE
Add an option to provide firmware type

### PR DESCRIPTION
**Pull request by Reggian**
When creating a firmware from zip a parameter can be supplied in order
to select which firmware type to use.

### CODE REVIEW

**Comment by philips77** [comment]
Hi, thanks for the pull request. I'll have a deeper look in couple of days, but it looks good :)

**Comment by philips77** [comment]
Hi, why did you set these references as weak? How does it help?

**Comment by Reggian** [comment]
Hi, the weak references have nothing to do with this pull request. I wanted to make a separate pull request for this (I am new to GitHub contributions etc.) and it appeared here.

Imagine this scenario with current implementation:
1) MyClass instance creates a DFUServiceInitiator instance and adds itself as a delegate (DFUServiceInitiator retains MyClass).
2) DFUServiceInitiator instance then creates the DFUServiceController instance which retains it via DFUExecutor (DFUServiceController retains DFUExecutor and DFUExecutor retains DFUServiceInitiator).
3) MyClass instance needs to hold on to DFUServiceController instance (MyClass retains DFUServiceController).

As you can see we have a retain cycle.
It can be easily broken by making the delegates stored as weak (and it is also a common practice to do so).

**Comment by philips77** [comment]
Ok, get it. You are right. I'm forcing one cyclic ref Executor- Peripheral (afair) to keep the DFU going even when you don't care about the dfu controller, or user dismissed the view controller (DFU delegate). But I did not think about this case.

**Comment by Reggian** [comment]
> I'm forcing one cyclic ref Executor- Peripheral (afair) to keep the DFU going even when you don't care about the dfu controller, or user dismissed the view controller (DFU delegate).

Are you sure you want this kind of behaviour?
Is the Executor- Peripheral cycle ever broken? I have put a log in Peripheral's deinit method and it was never called.
In my opinion it is the App's responsibility to retain the DFU (e.g. by holding on to DFUServiceController).
Either that or make sure that all objects are properly "released" after procedure ends (e.g. success, abort, fail etc.)

**Comment by philips77** [comment]
The app doesn't have to use DFU Controller. If you just call initiator.start(), then the method that had the initiator reference finishes, the DFU objects were disposed. Even if they had a reference to the loggerDelegate or DFU delegate nothing referenced them.
When the DFU finishes, successfully or not, the cycle is broken in DFUPeripheral.

**Pull request merged**
