### PR TITLE
Migrated to Swift 3 Release

### PR DESCRIPTION
**Pull request by pruthvikar**
Did an initial migration to Swift 3

### CODE REVIEW

**Comment by jovirus** [comment]
Looks good

**Comment by xRuby** [comment]
@jovirus   why convert swift3.0  still  error,  i use pod update and convert 3.0

**Comment by jovirus** [comment]
@xRuby Hi, We are currently working on the migration to swift3. Please kindly wait for the new release.

**Comment by klemenzagar91** [comment]
@jovirus can you tell us how much will approximately take you to finish this. Will it be hours, days?

**Comment by jovirus** [comment]
@klemenzagar91 Thank you for following Nordic open source project, we will put this on first priority.

**Comment by klemenzagar91** [comment]
oh. and one question, will this be also implemented in the cocoapods version of your library. Sometimes I found that those two projects aren't always in sync. Am I wrong about this? 

Thanks for all your work so far. I really appreciate your help.

**Comment by mostafaberg** [comment]
@klemenzagar91 Sorry for the delayed response, work will be resumed on the DFU library on all repositories , we will basiclaly add Swift3.0 support, old versions will be deprecated eventually.
also all repositories will be brought up to the cocoapods repository at the same time, yes they are not always in sync and we will resolve this issue too in the very near future.

This task will probably be completed within the upcoming working week!

**Pull request merged**
