### PR TITLE
Fix documentation warnings.

### PR DESCRIPTION
**Pull request by sschiffli**

### CODE REVIEW

**Comment by mostafaberg** [comment]
Thanks for the fixes, but what warnings where you seeing ?

**Comment by sschiffli** [comment]
I think it might have something to do with having an obj-c project since the warning is coming from the generated iOSDFULibrary-Swift.h file, but here is my Xcode screenshot:
ios-dfu-warnings

**Comment by mostafaberg** [comment]
Ofcourse! That makes sense, thanks a lot 👍

**Comment by philips77** [comment]
Will be published in 3.0.3 in few moments.

**Comment by philips77** [comment]
Released in 3.0.3.

**Pull request merged**
