### PR TITLE
Add xcodeproj file for library.

### LINKED ISSUE #46: Cannot include project into workspace without using Cocoapods
I tried to follow the docs but I cannot find the `DFULibrary.xcodeproj` file. Am I missing something? I don't use Cocoapods nor Carthage.

### PR DESCRIPTION
**Pull request by guidomb**
This PR is intended to fix #46. I have created an Xcode project for to be able to work on the library. By having an Xcode project, contributors can easily work on the project and people that wants to include this library without using Cocoapods or Carthage can do so by including this project file into their project's workspace.

### CODE REVIEW

**Review by philips77 — COMMENTED** [review]
Hi, could you also have a look at Version3 branch. It is about to replace the current version soon.

**Comment by guidomb** [comment]
@philips77 Some classes were not compiling that is why I decided to based my work with the `master` branch. I didn't take a closer look but if the only changes that were made on branch `Version3` are in the same source files, it is just a matter of copy pasting those sources. But let mw know how to proceed.

**Comment by guidomb** [comment]
Some important difference is that if this change gets merged people using the library should import it by doing

**Objc**
```objc
@import iOSDFULibrary;
```

**Swift**
```swift
import iOSDFULibrary
```

**Comment by mostafaberg** [comment]
Gave that a try and it unfortunately breaks our current configuration, will need to find a better solution, will look into it and keep you updated on the issue https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/issues/46

thanks for your work :) sorry that we couldn't merge it

**Comment by guidomb** [comment]
@mostafaberg What do you mean by

>  unfortunately breaks our current configuration

**Comment by mostafaberg** [comment]
I was refering to the cocoapods setup in the project

**Comment by guidomb** [comment]
I can fix it if you tell me what is wrong with it. I don't use CocoaPods, I use Carthage and that is why my emphasis was on making this work for Carthage and also as stand alone Xcode project. But I would like to know if you are willing to merge this if it works with CocoaPods too.

**Comment by mostafaberg** [comment]
Another issue was the Zip module, it is no longer required into have a cartfile with the Zip dependency since it's already supplied by the bundled cocoapods installation, so there is no way to build the standalone project without having a Cartfile with the Zip dependency

**Comment by mostafaberg** [comment]
Ok give me a few mins i'll be running to a meeting and when i'm back i'll get in touch with you about those issues, we will ofcourse merge a working PR, we would like to work further on that to give you all the possible methods of installation 👍

**Comment by guidomb** [comment]
Sure no worries. Just to be clear what do you mean by 

>  Zip dependency since it's already supplied by the bundled cocoapods installation, so there is no way to build the standalone project without having a Cartfile with the Zip dependency

Because in the `master` branch this project declares Zip as a dependency in the `podspec` file [here](https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/blob/master/iOSDFULibrary.podspec#L28), so you are still depending on it.

That line in the `podspec` is the equivalent of having a `Cartfile` with the same dependency. Unfortunately having to maintain more than one installation methods has this tradeoffs (having to maintain different files that declare dependencies) but most popular projects deal with this. Currently there is not better way around this.

**Comment by mostafaberg** [comment]
Exactly , that's the problem, we only have the Zip in `podspec` now, and no longer have a `cartfile`, so when you install the library via `Carthage` you will now automatically get the `Zip.framework` without having it as a carthage dep. it's already in our project as a shared scheme

**Comment by mostafaberg** [comment]
Back at work now and reviewing !, will keep you updated !

**Comment by mostafaberg** [comment]
Ok I have to apologize for closing this too early without verifying the issue was in my Xcode setup, got a different error this time and clearing the Xcode caches and restarting resolved it, I'm verifying installation works on all methods now and if all works i'll merge the PR right away ! 👍  great work!

**Comment by guidomb** [comment]
Cool! Maybe the best option would be to get the latest update in `master` in this PR first. I'll try to update this PR by the end of my day (I am in GMT -03:00).

**Comment by mostafaberg** [comment]
Awesome !, Cocoapods works now, but there might be minor changes i have to do to fix the Zip module redefinition, if i do i'll just push that here and you can do any required work later. problem so far is building with carthage uses your new project instead of the old iOSDFULibrary project, meaning the Zip dependency now has changed and that iOSDFULibrary is built twice, once for the old project we had and one for the new project file you added, i'll verify if this and let you know, but i think we're on the right path now :) thanks a lot !

**Comment by mostafaberg** [comment]
So far debugging the following issue:
create a new cartfile with this PR as she source repo/branch, then run `carthage update --platform iOS`

this will end up with the following:
```
*** Fetching
*** Checking out  at "d68e10b55ea22f90f0d1f5d82590c221cac91a72"
*** xcodebuild output can be found in /var/folders/43/r7glptjn1_1f6k489s5r994w0000gn/T/carthage-xcodebuild.iDYCEY.log
*** Building scheme "iOSDFULibrary" in iOSDFULibrary.xcworkspace
*** Building scheme "iOSDFULibrary" in iOSDFULibrary.xcworkspace
```

No `Zip.framework` is built, only `iOSDFULibrary` twice, can you repro this on your side ?

**Comment by guidomb** [comment]
I get the following output

```
*** No Cartfile.resolved found, updating dependencies
*** Cloning IOS-Pods-DFU-Library
*** Cloning Zip
*** Checking out Zip at "0.6.0"
*** Checking out IOS-Pods-DFU-Library at "c4acc9b901a52930481150994156eb9042308930"
*** xcodebuild output can be found in /var/folders/gf/dslbq4t94zg44sz7wnk2lg2r0000gp/T/carthage-xcodebuild.2q4vjh.log
*** Building scheme "Zip OSX" in Zip.xcodeproj
*** Building scheme "Zip tvOS" in Zip.xcodeproj
*** Building scheme "Zip" in Zip.xcodeproj
*** Building scheme "iOSDFULibrary" in iOSDFULibrary.xcworkspace
*** Building scheme "iOSDFULibrary" in iOSDFULibrary.xcworkspace
```

when running `carthage bootstrap` with the following `Cartfile`

```
github "guidomb/IOS-Pods-DFU-Library" "xcodeproj"
```

**Comment by guidomb** [comment]
and the running `ls Carthage/Build/iOS ` I get

```
1FEC455C-551A-34FE-8954-772F573DBF8B.bcsymbolmap 57F720FC-CC92-30ED-822B-A770A2065601.bcsymbolmap iOSDFULibrary.framework
2E893D53-2DFC-3826-9EB7-B4C38FF93DF5.bcsymbolmap Zip.framework                                    iOSDFULibrary.framework.dSYM
3238527C-7AFC-3B58-81D2-BFF292650985.bcsymbolmap Zip.framework.dSYM
```

**Comment by mostafaberg** [comment]
A bit different than what i saw, but the interesting part is still:
```
*** Building scheme "iOSDFULibrary" in iOSDFULibrary.xcworkspace
*** Building scheme "iOSDFULibrary" in iOSDFULibrary.xcworkspace
```

will look deeper into that tomorrow, i'm working on another solution and will also update you tomorrow

**Comment by mostafaberg** [comment]
So far here are the issues i found:

- iOSDFULibrary project is built twice due to the fact that there is a `iOSDFULibrary.xcodeproj` and `iOSDFULibrary.xcodeproj`, `iOSDFULibrary.xcworkspace`in the Example directory.

- The current setup provides `Pods_iOSDFULibrary_Example.framework` via the built framework in the  DerivedData directory, not sure why or what were you trying to accomplish ?

- Building via Carthage is still broken due to the `Minizip.modulemap` being redefined due to the fact that `Zip.framework` is built in `Checkouts/iOSDFULibrary/Carthage/Checkouts/Zip` and in `Checkouts/Zip`, I'm currently working on a fix with that and getting in touch with some of the devs to see what can be done here, to reproduce try to use this PR as a dependency to a new project and you'll get the issue

- In the `iOSDFULibrary.xcodeproj`, `Zip.framework` is imported directly into via the Carthage Builds, which is not a common practice for carthage, this disallows 3rd party devs to use their own version of `Zip` in the project, the usual way of implementing that to be able to build the project is to create a workspace that has both `iOSDFULibrary.framework` and `Zip.framework`, this enables 3rd parties to use only `iOSDFULibrary.xcodeproj` with any version of `Zip.xcodeproj` when needed, current setup locks them out.

- I haven't tested this yet, but even though the example app works, it's not going to be available to the `pod try` command as it's not configured, now only `iOSDFULibrary.xcodeproj` or `Example/iOSDFULibrary.xcodeproj` will be built, which either won't include the example target, or will checkout the example but without the library

this will take a bit more time to work on, but i have something local that looks promising so far, but i need to get a solution to the module redefinition issue first.

sorry for the lengthy post :) just wanted to explain as much findings as possible

**Comment by guidomb** [comment]
Thanks for the update. I won't be able to do much this week but I am happy to keep working on this next week. Let me know what do you is the best direction moving forward. I plan to rebase this branch with the latest commits in `master`. Personally I think that the `Zip` dependency should not be included in this project and should be added by user of this library if they don't want to use either Carthage o CocoaPods.

**Comment by Looveh** [comment]
This PR seems to have been dormant for quite a while, is there any plan to close it? 

I'm currently working on a React Native wrapper for Nordic DFU (https://github.com/Pilloxa/react-native-nordic-dfu) and it would be very practical to be able to integrate this library with a .xcodeproj. 😄

**Comment by mostafaberg** [comment]
@Looveh Cool work !, actually this PR has seems to cause a few issues and was pushed to the backlog and never came up again due to very low requests, we still have it in the back of our heads and might have a fix soon, but it'll probably not be based off this PR.

What is it do you need to have though ? just an example project ?

**Comment by Looveh** [comment]
Ah I see!

It's an actual need that we'll have in production. We have developed a physical device based on the NRF52 series with a corresponding React Native app, that will among other things be responsible for relaying firmware updates to the device. 

We've got this working on Android already and feel confident that this approach will be very useful in production.  We're primarily developing the library for us to use in our final product, while making it open source in the process :)

If you're interested about us we're in closed beta atm, more info about us may be found on our website ;) https://pilloxa.com/.

Much appreciated!

**Comment by mostafaberg** [comment]
@Looveh I see, that's a very interesting project actually, I'll personally want one 👍 
Ok let's check out what can be done here, I'll take a look into this next week and let you know my findings and give you an ETA

**Comment by Looveh** [comment]
Awesome, thanks!

**Comment by mostafaberg** [comment]
@Looveh Sorry for taking too long, still looking into the case and getting back to you soon :) still don't have an ETA due to having a lot on our plate at the moment, but we are looking into it and it's not forgotten :)

**Comment by Looveh** [comment]
@mostafaberg Hi again! Have you had time to look into this yet? :)

**Comment by mostafaberg** [comment]
@Looveh Hi, sorry for not updating the thread earlier, yes i did take a look and i have a fix in the pipeline, it's my upcoming task after I finish what's currently being done on another project, as soon as I start working on the task i'll give you a heads up, just so I can estimate better, do you have a deadline that this fix **MUST** be done before ?

**Comment by Looveh** [comment]
@mostafaberg Hi again, I really appreciate you taking your time to do this! For us it would cause a delay in our roadmap if it isn't available by Aug 14.

**Comment by mostafaberg** [comment]
@Looveh No worries, we'll get this fixed ASAP before your deadline, i'll keep you updated as soon as I start working on the task 👍

**Comment by mostafaberg** [comment]
Quick update, working on the enhancement now, there are also other minor fixes that will be included while we're at it, will keep you update it during the progress

**Comment by mostafaberg** [comment]
@Looveh & @guidomb , I'm getting close to a fix , can you try this initial [feature branch](https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/tree/feature/ProjectFiles) and see if it'll work for you ?

The project file of interest would be `iOSDFULibrary.xcodeproj`, I have also integrated a `iOSDFULibrary.xcworkspace` that includes the `iOSDFULibrary.xcodeproj` as a development pod  with the demo app `Demo.xcodeproj`. but it's not required, this will be just for the `pod try` command.

**Comment by mostafaberg** [comment]
@Looveh any updates ?

**Comment by Looveh** [comment]
@mostafaberg Awesome! I'll know more by tomorrow afternoon, will let you know then :+1: Thanks!

**Comment by mostafaberg** [comment]
Perfect!, if things work as needed I'll do a new release with those changes on master

**Comment by Looveh** [comment]
@mostafaberg I'm unable to build the `iOSDFULibrary-iOS` project by itself, it gives me an error `Swift compiler error > No such module 'Zip'`. Any idea on how to get it working?

**Comment by mostafaberg** [comment]
it won't build by itself since it's a standalone project, it should however build `Zip` since it's there as a carthage dependency in the Cartfile, how are you building it ?

**Comment by Looveh** [comment]
@mostafaberg I was able to get `Zip` to build eventually, but it seems like the Swift -> Objective C header file `iOSDFULibrary-Swift.h` isn't auto generated for the target `iOSDFULibrary.framework`, any idea on how I might get that file to be generated and access classes/functions from Objective C?

**Comment by mostafaberg** [comment]
Well the swift header is actually very minimal, what is the contents of yours ? can you attach a test project that has that issue so i can see what's going on ? that file should be auto generated when you build and I don't see why yours won't generate ? strange

**Comment by Looveh** [comment]
@mostafaberg Sorry for coming back to you so late. I was able to get everything to compile! So I'd say this is ready for merge on my part :+1:

**Comment by mostafaberg** [comment]
@Looveh Perfect !, Will get that done next week !, sorry about the delays, but you can safely use that branch I have in your Podfile we will leave it for you a bit after it's been merge so nothing breaks for you and then remove it once you confirm it's ok on your side :)

**Comment by mostafaberg** [comment]
@Looveh Sorry about more delays, we have had some refactoring in the library that will invalidate the work I've done here, but it'll be revisited very soon and released !, thanks guys for hanging in there :)

**Comment by larryonoff** [comment]
I'm writing a library for my company project and as result this PR become actual for me. Is there any plans to merge it soon?

**Comment by philips77** [comment]
This PR is now outdated. Please, create a new one referencing this PR.

**Pull request closed without merging**
