### PR TITLE
Switch from Zip to ZIPFoundation

### PR DESCRIPTION
**Pull request by jlubawy**
Submitting this to get your input on switching from Zip to ZIPFoundation. This solves a lot of the dependency problems myself and others have encountered due to the minizip dependency in Zip. Problems such as "module minizip not found" or "duplicate minizip definitions".

The only downside to switching as far as I can tell is that ZIPFoundation raises the minimum iOS version from 8.0 to 9.0 (some compression APIs it uses were added in 9.0).

### CODE REVIEW

**Comment by philips77** [comment]
Thanks! iOS 9 is still good, as that's the maximum for iPhones 4S, as far as I remember. We'll have a look and come back to you. Please, ping us when it takes too long.

**Comment by jlubawy** [comment]
Thanks for considering this change. Just for completeness here are some of the minizip issues I referenced in case others have run into these issues:

* https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/issues/185
* https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/issues/190

**Comment by marcosiino** [comment]
Hi, any news about the switch from Zip to ZIPFoundation ? We are encountering many problems with the Zip pod too. 

Thanks!

**Comment by marcosiino** [comment]
I just saw that ZipFoundation has the same problem of Zip pod in its podspec, they both didn't specified the s.swift_version directive, and this causes build problems with project using swift < 4.x...

**Comment by alanfischer** [comment]
@marcosiino You are welcome to try a branch I have that uses SSZipArchive instead of ZipFoundation.  It is located here: https://github.com/alanfischer/IOS-Pods-DFU-Library/tree/ssziparchive

Either way, I would approve of Zip being replaced by something else in this project.  It is a large source of headache.

**Comment by philips77** [comment]
Hi @alanfischer @marcosiino @jlubawy,
I'm about to do an update to the DFU lib. Do you think this PR should be in the new release?

**Comment by philips77** [comment]
Ok, time up ;)
We had a chat here and decided to merge the PR. We can always revert it.

**Pull request merged**
