### PR TITLE
DFU UUID Helper

### PR DESCRIPTION
**Pull request by khoogheem**
Allow for changing the DFU UUIDs from the ones used in Internal Classes using a UUIDHelper singleton.   This will allow users to change from the standard UUID to custom UUIDs.

Also added a .jazzy file to allow for API Documentation to be built in the docs folder to provide HTML documentation of the API.

### CODE REVIEW

**Comment by MMooreGitHub** [comment]
Nice suggestion, @khoogheem. This would prove quite beneficial!

**Review by philips77 — CHANGES_REQUESTED** [review]
Please, fix the buttoless typo to buttonless

**Comment by khoogheem** [comment]
Should be fixed now ;)

**Review by mostafaberg — CHANGES_REQUESTED** [review]
Thanks a lot for the great efforts!

Here is my feedback:

1- This has to be a PR into develop and not master 👍 
2- The UUID Helper is a singleton, we would like to stay away from that, can you follow the android Library as a reference? the UUID's are given as parameters to the initiator instead, which is much cleaner. 
3- I would request to leave the documentation part out of this PR due to many reasons:

a. We do not want to pollute the codebase with documentation files that will trigger lots of new commits.

b. We do not want to have documentation for all internals, we just want to document how to start the DFU process and how to select the firmware files, and this is already done.

c. We don't know how that integrates with cocoa pods and Carthage, have you tested that? we don't want the docs to leak into projects that integrate our source.

d. This PR is for the DFU UUID Helper, we would like to have a PR do only one thing and not multiple so we can easily revert 👍 

Besides that, thanks a lot for the PR and the efforts to improve the DFU Library ! looking forward to your responses

**Comment by khoogheem** [comment]
1) Yep, next time I will remember to do it in Develop ;)
2) Given the current use of the Static Functions, the singleton was the clean approach, vs doing some more heavy changes.  However I think there is opportunity here to change it to a variable passed into the initiator
3) Here is my compromise... Leave the `.jazzy.yaml` in there so folks can create there own Docs (by default jazzy just does public interface).  I will remove the docs folder and add docs to `.gitignore`

**Comment by khoogheem** [comment]
Ok.  I reverted the .gitignore and commented out the section in the example for testing Custom UUIDs

**Comment by philips77** [comment]
Hi, we found some issue in this PR. We're working on resolving then. Automatic tests in example app stopped working, jumping to bootloader doesn't work. That's because you scan for dfuService.service now, which is null at that time. It used to take it from the class template (?).

**Pull request merged**
