### PR TITLE
Dispatching delegates in designated queues

### PR DESCRIPTION
**Pull request by philips77**
This PR should solve issue #249.
CC @DevAndArtist

There are still 3 calls for main dispatch queue. Do you have an idea how to solve it? I guess I should use the queue used for central manager to be consistent.

### CODE REVIEW

**Comment by philips77** [comment]
Ok, I guess that's it. Could you check if it works for you? Or at least if the API will work for you?

**Comment by DevAndArtist** [comment]
@philips77 thank you for the effort, I will add it tomorrow to our project and check how it behaves. Btw. I scanned over the patches and haven't seen any use of `dispatchPrecondition`, how did you verified the queue on which the code is being run?

**Comment by philips77** [comment]
The main reason for not using it is that I don't know how to use this method :)
I assume that all CBCentralManager and CBPeripheral delegate calls are done on a queue given in CBCentralManager connector. All other calls in the lib are called from one of the delegate methods, except from starting dfu, where the current queue is used, it delayed called, where I use the same queue explicitly. Isn't that enough?

**Comment by philips77** [comment]
Hello, any updates on this? I watched a video and I'm now pro in `dispatchPrecondition`, but still don't think it's necessary due to what I said earlier.

**Comment by DevAndArtist** [comment]
@philips77 not yet. I'm currently fixing other parts of our library which prevent me from being able to compile the project. I'll try to test your patch by the end of the day, I hope, and report back.

If you're interested to read more about `dispatchPrecondition` here is a Swift thread where I asked for some more clarifications: https://forums.swift.org/t/what-is-the-default-target-queue-for-a-serial-queue/18094

**Comment by philips77** [comment]
Other thing, `dispatchPrecondition` is available on iOS 10+ while DFU is now supported on 9.0+ (after migrating Zip -> ZipFramework in #251).

**Comment by philips77** [comment]
I'm thinking about merging the PR tomorrow and releasing 4.3.0 if you have no objections.

**Comment by DevAndArtist** [comment]
I finally updated to project to test the changes but I'm hitting an issue:

```
dyld: Library not loaded: @rpath/ZIPFoundation.framework/ZIPFoundation
  Referenced from: /private/var/containers/Bundle/Application/D5798A54-60A6-4F27-9BC1-F3E9AD9164B5/App.app/Frameworks/iOSDFULibrary.framework/iOSDFULibrary
  Reason: image not found
```

~Should I include the new dependency manually or are the projects dependencies messed up? (I'm using carthage to include the DFU lib.)~

You are missing a `cartfile` with the new dependency to ZIPFoundation, otherwise Carthage has now idea that this project depends on it.

**Comment by DevAndArtist** [comment]
Resolved the dependency here and the framework gets added into the app bundle, but I'm hitting the next issue and unable to run the app.

```
dyld: Library not loaded: @rpath/ZIPFoundation.framework/ZIPFoundation
  Referenced from: /private/var/containers/Bundle/Application/6768A1C7-5C6E-471B-9969-F84AEFE42EA3/App.app/Frameworks/iOSDFULibrary.framework/iOSDFULibrary
  Reason: Incompatible library version: iOSDFULibrary requires version 1.0.0 or later, but ZIPFoundation provides version 0.0.0
```
I'm currently out of ideas why this issue happens. I cleared Derived Data and clean build the project.

**Comment by DevAndArtist** [comment]
I resolved the issue above, it's an issue `ZIPFoundation` has, I'm not sure if my PR will be approved. I found the solution in a different project after searching the web for it: https://github.com/jpsim/Yams/issues/131

I fixed the issue here:
https://github.com/weichsel/ZIPFoundation/pull/91

---
In your case you still need to add a `cartfile` so Carthage can pull `ZIPFoundation`.

**Comment by philips77** [comment]
I've created `cartfile` with 
```
github "weichsel/ZIPFoundation" ~> 0.9
```
in the main directory. Is there anything else needed for me to push?

**Comment by philips77** [comment]
Btw, we didn't have `cartfile` before switching to ZipFoundation, or at least I don't see it. Was it working for you before, or you had to include that dependency in your `cartfile`?

**Comment by DevAndArtist** [comment]
That's a good question. To be honest I'm not sure how Carthage previously pulled `Zip.framework`. It just didn't worked for me this time.

---

I'm fixing some internal `dispatchPrecondition` cases related to the changes made here. Give me an hour or so, I'll report if I could flash without issues.

**Comment by DevAndArtist** [comment]
Okay I could flash multiple times without any issues. Feel free to merge.

**Comment by philips77** [comment]
I've added `Cartfile`. Is that the right place for it?

**Comment by DevAndArtist** [comment]
Looks good on my end, Carthage can now pull `ZIPFoundation` correctly, the only requirement for the project to run correctly is them to merge my PR.

**Pull request merged**
