### PR TITLE
Fix ZIPFoundation version for Carthage

### PR DESCRIPTION
**Pull request by piellarda**
This PR fix the Carthage integration.

### CODE REVIEW

**Comment by piellarda** [comment]
Anyone to get this approved? carthage builds have been crashing since 4.7.0.

**Comment by philips77** [comment]
Hello,
Sorry, I must have missed your PR.
Does the new version fix this issue? I can merge it today.

**Comment by piellarda** [comment]
It's not really a new version, it's just the same as the podspec declares.

**Comment by philips77** [comment]
I will release a new version today.

**Pull request merged**
